In [2]:
import numpy as np

In [ ]:
from _lda_helpers import mean_change_2d, gamma_update

In [ ]:
A = np.random.rand(1000,1000)
B = np.random.rand(1000,1000)

In [ ]:
%timeit mean_change_2d(A, B)
%timeit np.abs(A - B).mean()

In [ ]:
%timeit A / A.sum(0)
%timeit normalize_matrix_cols(A)

In [ ]:
b = np.random.rand(5)
A = np.random.rand(5, 10000)

In [ ]:
%timeit b + np.sum(A, 1)
%timeit gamma_update(b, A)

In [ ]:
from sklearn.preprocessing import normalize

In [ ]:
C = np.random.rand(5, 10000)

In [ ]:
%timeit C / C.sum(0)
%timeit normalize(C, copy=False, norm="l1", axis=0)

Experiments with joblib

In [ ]:
from joblib import Parallel, delayed
import numpy as np

In [ ]:
class A:
    def __init__(self):
        self.X = np.random.rand(3,3)
        
a = A()

In [ ]:
def assign_ones_to_first_col(a):
    m = a.X[:,:1]
    m = np.ones(a.X.shape[0])
    
assign_ones_to_first_col(a)

In [ ]:
a.X

In [12]:
A = np.random.rand(3,3)

In [15]:
A

array([[ 0.04017214,  0.66658808,  0.18434059],
       [ 0.86440693,  0.52765998,  0.42365461],
       [ 0.43569649,  0.86995523,  0.09909188]])

In [16]:
(A.T / np.sum(A, 1)).T

array([[ 0.04508147,  0.74805014,  0.20686839],
       [ 0.47606801,  0.29060623,  0.23332576],
       [ 0.31016087,  0.61929823,  0.0705409 ]])

In [17]:
A / np.sum(A,1)[:, np.newaxis]

array([[ 0.04508147,  0.74805014,  0.20686839],
       [ 0.47606801,  0.29060623,  0.23332576],
       [ 0.31016087,  0.61929823,  0.0705409 ]])